# Generated by Django 4.2.2 on 2023-07-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='time',
            new_name='created_at',
        ),
    ]
